name: CI

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        cpp-version: '14'  # Adjust the C++ version as needed

    - name: Build
      run: |
        make
        # Optionally, you can run tests here

    - name: Display list of files
      run: ls

    - name: Show job status
      run: echo "Job status is ${{ job.status }}"
